---
title: "Skill Check 2.1"
subtitle: "CPSC 292 Section -- (Instructor last name)"
author: "Names of your group members"
date: "10/06/2023"
output: html_notebook
---

## Skill Check 2.1 -- Geometric Object Types

```{r setup, include=FALSE}
# Loading required libraries
# Do not alter this section of code!
library(ggplot2)
```

### Agreement 

This Skill Check is meant to be an assessment of your ability to creatively execute several learning objectives at once by visualizing information in specific styles and provide code for your fellow classmates. 

You will be assessed together with your group members for this Skill Check. Part of how you are assessed is your ability to work together. 

You may use any resource, either online or physical, to complete the work. This includes: 

 - Any help forum or website (e.g. StackOverflow) questions that already exist.
 - Any notes, code, slides, papers, or previous feedback from the instructor.
 - Any books, online or physical.
 - Scholarly works such as papers. 
 
It DOES NOT include:

 - Help from generative artificial intelligence such as ChatGPT.
 - Help from homework websites such as Course Hero or Chegg.
 
If you use work outside normal course resources (textbooks, lecture notes, slides, code, or instructor feedback), you are expected to cite the work by providing a URL to the source near the place that the code was used.

### Skill Check Instructions

For the next two class periods, you will work in a small group to prepare some sample code for using each of the following groups of geometric objects for your classmates: 

 1. `geom_point()`, `geom_line()`, `geom_qq_line()`
 2. `geom_bar()`, `geom_boxplot()`, `geom_violin()`
 3. `geom_histogram()`, `geom_density()`, `geom_dotplot()` 
 4. `geom_map()`
 5. `geom_raster()`, `geom_tile()`, `geom_contour()`
 6. Other geoms: [ggplot extension gallery](https://exts.ggplot2.tidyverse.org/gallery/)
 
Be ready to give a short presentation on each graph type. Let us know the following things: 

 * what does the plot look like (present an example of each)
 * what data are appropriate for use (categorical, continuous, etc)
 * what does the plot tell us about the data (generally)
 
You'll be responsible for turning in an R Markdown file with the example code as part of your Skill Check 2.1. 

Due date for RMD file: 10/9/2023 before class starts
